name: Count Files (develop)

on:
  push:
    branches:
      - develop

jobs:
  count-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print branch name
        run: |
          echo "Branch name: ${{ github.ref }}"

      - name: Count files (develop)
        run: |
          file_count=$(find . -type f | wc -l)
          echo "Number of files in repository: $file_count"
